Expressions with priorities and testing
alt-romes/programmer-calculator pull request #56
Opened 2021-02-08 17:41 UTC by alt-romes

I implemented a parser that cleans up the code A LOT, and implements expressions with priorities.

All

2021-02-09 10:14 UTC, alt-romes commented
@DevManu-de perhaps you could run a valgrind check for me, I would have to install a virtual machine for it

2021-02-09 10:18 UTC, DevManu-de commented
@alt-romes you made many changes I will try to get a proper review of the code out today and all the necessary checks.

2021-02-09 10:20 UTC, alt-romes commented
fantastic ! take your time, it would be good to have a good review indeed.

thank you

2021-02-09 16:12 UTC, DevManu-de requested changes
Hello @alt-romes,

I have found several problems.

1. Problem
If I enter a number and an operator `1+` I receive an assert
`pcalc: src/parser.c:338: parse_stdop_expr: Assertion parser->pos < parser->ntokens' failed.`

2. Problem
After entering `1` and exit then valgrind reports
```
==481962== Memcheck, a memory error detector
==481962== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==481962== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==481962== Command: ./pcalc
==481962==
==481962==
==481962== HEAP SUMMARY:
==481962==     in use at exit: 1,389,731 bytes in 268 blocks
==481962==   total heap usage: 291 allocs, 23 frees, 1,400,130 bytes allocated
==481962==
==481962== 8 bytes in 1 blocks are definitely lost in loss record 1 of 45
==481962==    at 0x483E77F: malloc (vg_replace_malloc.c:307)
==481962==    by 0x10C98E: create_exprtree (parser.c:368)
==481962==    by 0x10C814: parse_number (parser.c:330)
==481962==    by 0x10C512: parse_atom_expr (parser.c:263)
==481962==    by 0x10C3B2: parse_prefix_expr (parser.c:198)
==481962==    by 0x10C884: parse_stdop_expr (parser.c:340)
==481962==    by 0x10C2DF: parse_mult_expr (parser.c:173)
==481962==    by 0x10C884: parse_stdop_expr (parser.c:340)
==481962==    by 0x10C28D: parse_add_expr (parser.c:163)
==481962==    by 0x10C884: parse_stdop_expr (parser.c:340)
==481962==    by 0x10C238: parse_shift_expr (parser.c:153)
==481962==    by 0x10C884: parse_stdop_expr (parser.c:340)
==481962==
==481962== LEAK SUMMARY:
==481962==    definitely lost: 8 bytes in 1 blocks
==481962==    indirectly lost: 0 bytes in 0 blocks
==481962==      possibly lost: 0 bytes in 0 blocks
==481962==    still reachable: 1,389,723 bytes in 267 blocks
==481962==         suppressed: 0 bytes in 0 blocks
==481962== Reachable blocks (those to which a pointer was found) are not shown.
==481962== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==481962==
==481962== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

3. Problem
I wasnt able to use the `-c` flag.
If i use the `-c` flag (alone) then it prompts me for input and after giving input nothing changed.
```
./pcalc -c
Decimal: 0, Hex: 0x0, Operation:
1+1
Decimal: 0, Hex: 0x0, Operation:
1
Decimal: 0, Hex: 0x0, Operation:
```

4. Problem
After multiple attemps I want able to get the test cases working. I started it with `./run-tests.sh` and it seems that it is somehow stuck in an infinite loop.
I tried finding the problem but wasnt successful and thought you can fix it way better than I.

I left some comments on the code.

After these problems are resolved I will make an even deeper review.

DevManu-de

2021-02-09 17:54 UTC, alt-romes commented on src/main.c
> +            sweepline(inputwin, 1, 22);
Yes, I'm pretty sure that if you don't have that sweep line and insert a big number (for example 11111111) followed by a small number (222) you'll probably still have the rest of the 1's there.

2021-02-09 18:00 UTC, alt-romes commented on src/parser.c
> +static exprtree parse_number(parser_t);
Functions are static because they are used just by this file, and are not to be used by other files.
The functions declared in the header file are the functions available for other files that import that header to use.

I hope that's clear/correct enough

2021-02-09 18:42 UTC, alt-romes commented
Thank you @DevManu-de
I'm working on the problems.

The weirdest one is the tests one, it was working perfectly, I'm gonna see what happened in the commits and fix it.

It shouldn't be too long before you can help the code be better with the next review

Thank you :)

2021-02-09 19:34 UTC, alt-romes commented
I've fixed both 1, 3 and 4.

I can't however figure out Valgrinds problem. I would have to look at it more closely, but I added some lines to debug the amount of tokens, trees and parsers created and freed, and they all match... my new commit shows this

Later on we'll need to delete this debugging information so that it passes the tests again.

Let me know what else you can find, I really need a second pair of eyes here (or more :) )

Thank you so much,
~romes

2021-02-09 19:42 UTC, DevManu-de commented on src/parser.c
> +static exprtree parse_number(parser_t);
I have to admit that I was wrong. I just wasnt aware that `static` can also be used as an access control described in this stack overflow qustion.

https://stackoverflow.com/questions/572547/what-does-static-mean-in-c
> Is used widely as an "access control" feature. If you have a .c file implementing some functionality, it usually exposes only a few "public" functions to users. The rest of its functions should be made static, so that the user won't be able to access them. This is encapsulation, a good practice.

Im sorry for the inconvenience I should have checked that earlier.
DevManu-de

2021-02-09 19:58 UTC, alt-romes commented on src/parser.c
> +static exprtree parse_number(parser_t);
Alles gut :+1:

2021-02-09 20:04 UTC, DevManu-de commented
I may have found the problem with valgrind. I will try to make a pr soon.

2021-02-09 20:18 UTC, DevManu-de commented
I have found another problem.
If I enter `3+-` then pcalc crashes `pcalc: src/parser.c:352: parse_stdop_expr: Assertion `parser->pos < parser->ntokens' failed.`

2021-02-09 22:21 UTC, alt-romes commented
@DevManu-de I found one of the sources of the memory leak, please check the most recent commit before proceeding.

I'm also taking care of `3+-` and other invalid expressions.

For now I'm applying a quick fix -> invalid expressions (i.e. opening a parenthesis but not closing it) give weird results because parts of the expression are evaluated to zero.

Ideally, an error message would be displayed when the user inputs an invalid expression.
I still haven't figured out the best way to handle the errors. I thought perhaps the expression could have another type ERR_TYPE, and somehow those would be handled and the error displayed... For now I want to get the basic version with the quick fix working fully.

Thank you,
~romes

2021-02-09 23:47 UTC, alt-romes commented
@DevManu-de I've tested it more extensively and added/fixed multiple things

Please let me know if anything still isn't functioning properly, and if there are still memory leaks.

I think we're approaching a good version of this, able to be put into production.

Thank you for your help,
~romes

2021-02-10 09:21 UTC, DevManu-de commented on src/main.c
> +            sweepline(inputwin, 1, 22);
In my test this never happend but if you experienced otherwise we should keep it.

2021-02-10 10:48 UTC, alt-romes commented on src/main.c
> +            sweepline(inputwin, 1, 22);
You're correct. I checked and tested. I was confusing this line with line 134 from `draw.c`
Thank you !

2021-02-10 13:51 UTC, DevManu-de commented
I think most of the memory leaks are fixed but the remaining one (same as in my review) still stays.

```
==346237== Memcheck, a memory error detector
==346237== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==346237== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==346237== Command: ./pcalc
==346237==
==346237==
==346237== HEAP SUMMARY:
==346237==     in use at exit: 1,389,731 bytes in 268 blocks
==346237==   total heap usage: 291 allocs, 23 frees, 1,400,130 bytes allocated
==346237==
==346237== 8 bytes in 1 blocks are definitely lost in loss record 1 of 45
==346237==    at 0x483E77F: malloc (vg_replace_malloc.c:307)
==346237==    by 0x10CB64: xmalloc (xmalloc.c:7)
==346237==    by 0x10CB05: create_exprtree (parser.c:407)
==346237==    by 0x10C92E: parse_number (parser.c:361)
==346237==    by 0x10C62C: parse_atom_expr (parser.c:294)
==346237==    by 0x10C492: parse_prefix_expr (parser.c:220)
==346237==    by 0x10C9E7: parse_stdop_expr (parser.c:379)
==346237==    by 0x10C385: parse_mult_expr (parser.c:187)
==346237==    by 0x10C9E7: parse_stdop_expr (parser.c:379)
==346237==    by 0x10C333: parse_add_expr (parser.c:177)
==346237==    by 0x10C9E7: parse_stdop_expr (parser.c:379)
==346237==    by 0x10C2DE: parse_shift_expr (parser.c:167)
==346237==
==346237== LEAK SUMMARY:
==346237==    definitely lost: 8 bytes in 1 blocks
==346237==    indirectly lost: 0 bytes in 0 blocks
==346237==      possibly lost: 0 bytes in 0 blocks
==346237==    still reachable: 1,389,723 bytes in 267 blocks
==346237==         suppressed: 0 bytes in 0 blocks
==346237== Reachable blocks (those to which a pointer was found) are not shown.
==346237== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==346237==
==346237== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

This memory leak comes from the `long long*` in the `exprtree->value`.
Either it never `free`d or the pointer is set to a new pointing location without `free`d.

After looking aroung the code for a fix I descoverd that the `free_exprtree` doesnt `free` `expr->value`. I added that `free` and it seemed to work but it crashses if i input `1++` or `1+1`.
Valgrind didnt show the leak anymore after I added this.
So maybe this is the fix but there is still a logic problem in the code.

This is the crash responde.
`free(): invalid pointer`
So I assume that `value` is set to a new pointing location maybe to something not in the heap and thus failing `free`.

DevManu-de

2021-02-10 14:03 UTC, alt-romes commented
@DevManu-de Thank you for your accurate finding!
I think I fixed the memory leak and the tests are all still passing.

Please let me know how else I can better the code and about still existing memory leaks.

Thank you
~romes

2021-02-10 15:14 UTC, DevManu-de commented
I tested the memory fix and I wasnt able to find any problems.
Also valgrind cannot find any leaks. :)

2021-02-10 16:27 UTC, merged