Colors
alt-romes/programmer-calculator pull request #66
Opened 2021-08-05 18:55 UTC by alt-romes

This PR adds colours to the `pcalc` interface.

@DevManu-de, I've tweaked the colours and fixed the segmentation fault bug. Do you think you can double check them on your terminal for readability and "aesthetic" ?

I'm still wondering if colours should be turned off by default or the other way around.

Let me know what you think,
~romes

2021-08-05 19:14 UTC, DevManu-de commented
@alt-romes this looks really good so far.
Maybe you can add to the `README.md` that `pcalc will always try to start with colors enabled but will disable them if no colors are available or turned off with flag -n`

2021-08-23 13:56 UTC, DevManu-de requested changes
Improvement idea for preventing duplicate code and improving readability.

2021-08-23 13:56 UTC, DevManu-de commented on src/main.c
> +            mvwprintw(inputwin, 1, 22, "%s", in);
I think this `if` should be part of the function `mvwprintw_colors` to prevent possible duplicate code.
Same should go for `wprintw_colors`.

2021-11-15 23:34 UTC, merged

2021-11-15 23:34 UTC, alt-romes commented
Hello,

After finding some color issues across different terminals, and because it's hard to please everyone with one colorscheme, I've disabled colors by default and will merge this onto main

Colors can be enabled with `-c` or `--colors`

Thank you for this feature
~romes